version: '3.4'

services:
  snmp-agent-simulator:
    container_name: snmp-agent-simulator
    build:
      context: /mnt/d/github/snmp-agent-simulator/
      dockerfile: Dockerfile
    ports:
      - '40000-50000:40000-50000/udp'   
    networks:
      - smartpack4

networks:
  smartpack4: