export const MessagePart = {
  MESSAGE: 'MESSAGE',
  VERSION: 'VERSION',
  COMMUNITYSTRING: 'COMMUNITYSTRING',
  PDU: 'PDU',
  REQUESTID: 'REQUESTID',
  ERROR: 'ERROR',
  ERRORINDEX: 'ERRORINDEX',
  VARBINDLIST: 'VARBINDLIST',
  VARBIND: 'VARBIND',
  OID: 'OID',
  VALUE: 'VALUE',
};

export const MessagePartBytes = {
  TYPE: 0,
  LENGTH: 1,
  VALUE: 2,
};

export const ComplexDataType = {
  SEQUENCE: 0x30,
  GETREQUEST: 0xA0,
  GETNEXTREQUEST: 0xA1,
  GETRESPONSE: 0xA2,
  SETREQUEST: 0xA3,
  TRAP: 0xA4,
  GETBULKREQUEST: 0xA5,
  INFORMREQUEST: 0xA6,
  SNMPV2TRAP: 0xA7,
};

export const PrimitiveDataType = {
  INTEGER: 0x02,
  OCTETSTRING: 0x04,
  NULL: 0x05,
  OBJECTIDENTIFIER: 0x06,
  IPADDRESS: 0x40,
  COUNTER32: 0x41,
  GAUGE32: 0x42,
  TIMETICKS: 0x43,
  OPAQUE: 0x44,
  COUNTER64: 0x46,
  NOSUCHOBJECT: 0x80,
  NOSUCHINSTANCE: 0x81,
  ENDOFMIBVIEW: 0x82,
};
